name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Specify Python version
  - tensorflow   # TensorFlow library for machine learning
  - scikit-learn
  - numpy
  - matplotlib
  - networkx
  - plotly
  - pillow  # For PIL (image handling)
  - pandas  # Added Pandas for data manipulation
  - pip
  - pip:
      - base64io  # For working with base64-encoded data streams